import { useEffect, useRef, useState } from 'react';
import type { FeatureCollection, MultiPolygon, Polygon } from 'geojson';
import { Check, MapPin, Plus, Save, Trash2 } from 'lucide-react';
import { api, ApiError } from './api';
import { ErrorBox, useApp } from './App';
import { closedPolygon, escapeMapLabel, loadYandexMaps, polygonsOf } from './yandexMaps';
import type { YMap, YMaps, YPolygon } from './yandexMaps';

type Feature = GeoJSON.Feature<Polygon|MultiPolygon,{id:number;name:string;active:boolean}>;
export default function DistrictMap(){
  const {user,meta,refresh,notify}=useApp();const admin=user.role==='ADMIN_OPERATOR';
  const container=useRef<HTMLDivElement>(null),map=useRef<YMap|null>(null),sdk=useRef<YMaps|null>(null);
  const editing=useRef<YPolygon[]>([]),background=useRef<YPolygon[]>([]),pick=useRef<(feature:Feature)=>void>(()=>{});
  const [features,setFeatures]=useState<Feature[]>([]),[selected,setSelected]=useState<number|null>(null),[name,setName]=useState(''),[active,setActive]=useState(true),[error,setError]=useState(''),[mapError,setMapError]=useState(''),[overlap,setOverlap]=useState(false),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[parts,setParts]=useState(0),[drawing,setDrawing]=useState(false);
  function load(){return api<FeatureCollection>('/districts').then(data=>setFeatures(data.features as Feature[])).catch(e=>setError(e.message));}
  useEffect(()=>{void load();},[]);
  useEffect(()=>{let cancelled=false;setMapError('');setReady(false);loadYandexMaps(meta.yandex_maps_api_key).then(api=>{if(cancelled||!container.current)return;sdk.current=api;map.current=new api.Map(container.current,{center:[72.603,61.099],zoom:13,controls:['zoomControl','typeSelector','fullscreenControl']},{suppressMapOpenBlock:true});setReady(true);}).catch(e=>{if(!cancelled)setMapError(e.message);});return()=>{cancelled=true;map.current?.destroy();map.current=null;editing.current=[];background.current=[];};},[meta.yandex_maps_api_key]);
  useEffect(()=>{if(!ready||!map.current||!sdk.current)return;for(const layer of background.current)map.current.geoObjects.remove(layer);background.current=[];for(const feature of features.filter(f=>f.properties.id!==selected)){for(const coordinates of polygonsOf(feature.geometry)){const layer=new sdk.current.Polygon(coordinates,{hintContent:escapeMapLabel(feature.properties.name)},{fillColor:feature.properties.active?'#80b39755':'#a3aba355',strokeColor:feature.properties.active?'#3d7e6c':'#8a9690',strokeWidth:2});layer.events.add('click',()=>pick.current(feature));map.current.geoObjects.add(layer);background.current.push(layer);}}},[features,selected,ready]);
  function clearEditing(){for(const polygon of editing.current){polygon.editor.stopDrawing();polygon.editor.stopEditing();map.current?.geoObjects.remove(polygon);}editing.current=[];setParts(0);setDrawing(false);}
  function reset(){clearEditing();setSelected(null);setName('');setActive(true);setError('');setOverlap(false);}
  function finish(){for(const polygon of editing.current){polygon.editor.stopDrawing();if(admin)polygon.editor.startEditing();}setDrawing(false);setOverlap(false);}
  function addPart(){if(!map.current||!sdk.current)return;finish();for(const part of editing.current)part.editor.stopEditing();const polygon=new sdk.current.Polygon([],{}, {strokeColor:'#d6a332',strokeWidth:3,fillColor:'#d6a33244',editorDrawingCursor:'crosshair'});polygon.events.add('geometrychange',()=>setOverlap(false));map.current.geoObjects.add(polygon);editing.current.push(polygon);polygon.editor.startDrawing();setParts(editing.current.length);setDrawing(true);}
  pick.current=(feature)=>{clearEditing();setSelected(feature.properties.id);setName(feature.properties.name);setActive(feature.properties.active);setOverlap(false);setError('');if(!sdk.current||!map.current)return;for(const coordinates of polygonsOf(feature.geometry)){const polygon=new sdk.current.Polygon(coordinates,{}, {strokeColor:'#d6a332',strokeWidth:3,fillColor:'#d6a33244'});polygon.events.add('geometrychange',()=>setOverlap(false));map.current.geoObjects.add(polygon);editing.current.push(polygon);if(admin)polygon.editor.startEditing();}setParts(editing.current.length);const bounds=map.current.geoObjects.getBounds();if(bounds)map.current.setBounds(bounds,{checkZoomRange:true,zoomMargin:30});};
  function removePart(index:number){const polygon=editing.current[index];polygon.editor.stopDrawing();polygon.editor.stopEditing();map.current?.geoObjects.remove(polygon);editing.current.splice(index,1);setParts(editing.current.length);setDrawing(false);setOverlap(false);}
  async function save(confirm=false){setError('');setBusy(true);try{finish();const coordinates=editing.current.map(p=>closedPolygon(p.geometry.getCoordinates()));if(!coordinates.length||coordinates.some(p=>p.length===0))throw new Error('Нарисуйте хотя бы один замкнутый полигон.');if(!name.trim())throw new Error('Укажите название микрорайона');await api('/districts'+(selected?'/'+selected:''),selected?'PUT':'POST',{name,active,geometry:{type:'MultiPolygon',coordinates},confirm_overlap:confirm});reset();await load();await refresh();notify('Границы сохранены. Микрорайоны фотографий будут пересчитаны.');}catch(e){if(e instanceof ApiError&&e.status===409&&typeof e.detail==='object'&&e.detail!==null&&'overlaps' in e.detail)setOverlap(true);setError((e as Error).message);}finally{setBusy(false);}}
  return <><header className="page-header"><div><span className="eyebrow">ГЕОГРАФИЯ РАБОТ · ЯНДЕКС КАРТЫ</span><h1>Микрорайоны</h1><p>Границы территорий для автоматического распределения фотографий.</p></div>{admin&&<button className="primary" onClick={reset}><Plus size={17}/>Новый микрорайон</button>}</header><ErrorBox error={mapError}/>{!meta.yandex_maps_api_key&&<p className="hint">Получите ключ JavaScript API в <a href="https://developer.tech.yandex.ru/keys/" target="_blank" rel="noreferrer">кабинете Яндекс.Карт</a> и укажите домен панели в ограничениях ключа.</p>}<div className="map-layout"><div className="map-canvas" ref={container} aria-label="Яндекс.Карта микрорайонов"/><section className="panel map-editor"><h2>{admin?(selected?'Редактирование границ':'Новый микрорайон'):'Микрорайоны города'}</h2><ErrorBox error={error}/>{admin&&<><label>Название<input value={name} onChange={e=>{setName(e.target.value);setOverlap(false);}} placeholder="Например, 12 мкр" maxLength={120}/></label><label className="checkbox"><input type="checkbox" checked={active} onChange={e=>{setActive(e.target.checked);setOverlap(false);}}/>Активен</label><div className="map-tools"><button disabled={!ready||drawing} onClick={addPart}><Plus size={15}/>Нарисовать часть</button><button disabled={!drawing} onClick={finish}><Check size={15}/>Закончить рисование</button></div><p className="hint">Ставьте вершины нажатием на карту. Несколько частей образуют один микрорайон. После завершения перетаскивайте вершины для изменения границ; внутренние кольца существующих полигонов сохраняются.</p>{Array.from({length:parts},(_,i)=><div className="district-row" key={i}><span>Часть {i+1}</span><button aria-label={'Удалить часть '+(i+1)} onClick={()=>removePart(i)}><Trash2 size={14}/></button></div>)}<button className="primary" disabled={busy||!ready} onClick={()=>save(overlap)}><Save size={16}/>{busy?'Сохранение…':overlap?'Подтвердить пересечение':'Сохранить границы'}</button>{overlap&&<p className="warning-text">Фото в пересечении будут попадать на ручную проверку.</p>}<hr/></>}<div className="section-title"><h3>Все территории</h3><span>{features.length}</span></div>{features.length===0?<p className="muted">Границы ещё не добавлены.</p>:features.map(f=><button key={f.properties.id} disabled={!ready} className={'district-row '+(selected===f.properties.id?'selected':'')} onClick={()=>pick.current(f)}><MapPin size={17}/><span>{f.properties.name}<small>{f.properties.active?'Активен':'Отключён'}</small></span>{selected===f.properties.id&&<Check size={16}/>}</button>)}</section></div></>;
}
